# Generated by Django 4.2.30 on 2026-07-18 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studySessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('file', 'File'), ('link', 'Link')], default='file', max_length=4)),
                ('file', models.FileField(blank=True, null=True, upload_to='session_resources/')),
                ('link_url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='studySessions.studysession')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
