"""
Django settings for studysphere project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(' ')
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost 127.0.0.1').split(' ')

MAINTENANCE_MODE = os.environ.get('MAINTENANCE_MODE', 'False').lower() == 'true'

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'channels',
    'storages',
    'accounts.apps.AccountsConfig',
    'groups',
    'messaging.apps.MessagingConfig',
    'notifications',
    'friends',
    'studySessions.apps.StudySessionsConfig',
    'flashcards',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'studysphere.middleware.MaintenanceModeMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'studysphere.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'studysphere.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600
    )
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Channels
ASGI_APPLICATION = 'studysphere.asgi.application'
REDIS_URL = os.environ.get('REDIS_URL')

if REDIS_URL:
    # --- TLS handling for Upstash (and any rediss:// provider) --------------
    #
    # Upstash requires TLS: its connection string uses the `rediss://` scheme.
    # channels_redis feeds each host entry to
    # `redis.asyncio.ConnectionPool.from_url(address, **rest)`, and django_redis
    # feeds CONNECTION_POOL_KWARGS to `redis.connection.ConnectionPool.from_url`.
    # In BOTH cases `from_url` inspects the URL scheme: `rediss://` selects the
    # SSLConnection class, `redis://` the plain one. The plain Connection rejects
    # any `ssl_*` kwarg with a TypeError, so SSL options are ONLY safe to pass
    # when the scheme is actually rediss:// — hence we gate them behind this flag
    # instead of setting them unconditionally.
    #
    # Cert verification: Upstash serves a normal CA-signed cert whose CN/SAN
    # matches the host, so redis-py's strict defaults (ssl_cert_reqs="required",
    # ssl_check_hostname=True) work as-is — we don't weaken them. The value is
    # read from REDIS_SSL_CERT_REQS purely as an escape hatch ("required" /
    # "optional" / "none") in case a future provider uses a self-signed cert;
    # leave it unset for Upstash.
    REDIS_IS_TLS = REDIS_URL.split("://", 1)[0].lower() == "rediss"
    _redis_ssl_kwargs = {}
    if REDIS_IS_TLS:
        _redis_ssl_kwargs["ssl_cert_reqs"] = os.environ.get(
            "REDIS_SSL_CERT_REQS", "required"
        )
    # Resilience tuning for channels_redis 4.3.x / redis-py 8.x on Render.
    #
    # A managed Redis instance can briefly stall (failover, maintenance, network
    # blip). We want to detect and recycle dead connections instead of blocking
    # forever — WITHOUT breaking the channel layer's normal operation.
    #
    # !!! socket_timeout on the CHANNEL LAYER must be > brpop_timeout (5s), NOT
    # unset. channels_redis's receive loop issues a *blocking* BZPOPMIN with a 5s
    # server-side timeout (RedisChannelLayer.brpop_timeout = 5), and redis-py uses
    # socket_timeout as the socket *read* timeout for that same call. redis-py 8.0
    # changed the DEFAULT socket_timeout from None to 5s (redis/_defaults.py), so
    # the read timeout now *ties* the blocking-pop timeout and loses the race —
    # raising `TimeoutError: Timeout reading from ...` on every idle connection.
    # This is the exact crash in the logs, and it happens even with no timeout set
    # in settings because the library default is 5. Setting it comfortably ABOVE
    # brpop_timeout lets the server-side pop return (empty) first on idle, while
    # still bounding a genuinely dead socket. Keepalive + health checks recycle
    # stale connections.
    #
    # API note: channels_redis feeds each "hosts" entry to
    # redis.asyncio.ConnectionPool.from_url(address, **rest), so connection options
    # live in the host dict itself — there is no separate "redis_kwargs" key.
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [
                    {
                        "address": REDIS_URL,
                        "socket_connect_timeout": 5,
                        "socket_timeout": 20,  # MUST stay > brpop_timeout (5s)
                        "socket_keepalive": True,
                        "health_check_interval": 30,
                        # Retry a command once if the socket times out, instead of
                        # letting the TimeoutError bubble up and kill the consumer.
                        # Safe alongside socket_timeout=20 > brpop_timeout=5: the
                        # blocking pop returns empty before the socket read fires.
                        "retry_on_timeout": True,
                        # ssl_cert_reqs (rediss:// only) — empty dict for redis://
                        **_redis_ssl_kwargs,
                    }
                ],
            },
        },
    }
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                # If Redis is down, treat it as a cache miss instead of raising
                # and 500-ing the request. WebSockets are the critical path here;
                # the cache is not worth taking the whole view down for.
                "IGNORE_EXCEPTIONS": True,
                # Safe here (unlike the channel layer): django-redis issues short,
                # non-blocking cache ops, so a read timeout bounds a genuine stall.
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
                "CONNECTION_POOL_KWARGS": {
                    "socket_keepalive": True,
                    "health_check_interval": 30,
                    "retry_on_timeout": True,
                    # ssl_cert_reqs (rediss:// only) — reaches SSLConnection via
                    # ConnectionPool.from_url. Empty dict for a redis:// URL, so
                    # nothing SSL-related is passed to the plain Connection.
                    **_redis_ssl_kwargs,
                },
            },
        }
    }
    # Log (don't raise) when django-redis swallows an exception via IGNORE_EXCEPTIONS.
    DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}